services:
  github-guard:
    container_name: github-guard
    image: article_scraper-github-guard:stable
    working_dir: /app/github-guard
    env_file:
      - ./github-guard/.env
    volumes:
      - ./github-guard/config.yaml:/app/github-guard/config.yaml:ro
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD-SHELL", "now=$(date +%s); last=$(cat /tmp/ok.ts 2>/dev/null || echo 0); [ $((now-last)) -lt 360 ]"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
