name: Train GPT Model

on:
  push:
    branches:
      - master

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build -t gpt-model .

      - name: Run GPT training
        run: docker run -v /mnt/nas:/app/data -v /mnt/nas/models:/app/models gpt-model python gpt_model.py

